#include "CodeGen.h"
#include <sstream>

// =============================================================================
// MAIN ENTRY POINT
// =============================================================================

void CodeGenVisitor::generate(ProgramNode* program) {

    // -------------------------------------------------------------------------
    // PRE-PASS: INCLUDES
    // Grimoire includes must appear FIRST in the C file — before all type
    // definitions — because headers may define types that our structs depend on.
    //
    // FIXED: The original emitted includes during Phase::TYPES, mixed in with
    // struct definitions. This breaks if a struct depends on a type from a header.
    // -------------------------------------------------------------------------
    emitLine("// ============================================================");
    emitLine("// GENERATED BY CGIL COMPILER v1.0");
    emitLine("// DO NOT EDIT BY HAND");
    emitLine("// ============================================================");
    emitLine("");
    emitLine("// --- System Includes ---");
    emitLine("#include <stdint.h>");
    emitLine("#include <stdbool.h>");
    emitLine("");

    // Emit all grimoire/pact includes now, before anything else.
    emitLine("// --- Cgil Grimoire Includes ---");
    currentPhase = Phase::TYPES; // Temporarily use TYPES so GrimoireDecl emits
    for (auto& decl : program->declarations) {
        if (auto* g = dynamic_cast<GrimoireDecl*>(decl.get())) {
            g->accept(*this);
        }
    }
    emitLine("");

    // -------------------------------------------------------------------------
    // PREAMBLE: CGIL RUNTIME STRUCTURES
    // These are always emitted, regardless of what the .gil source contains.
    // They are the fundamental C types that Cgil's type system builds on.
    // -------------------------------------------------------------------------
    emitLine("// --- Cgil Runtime Structures ---");
    emitLine("// scroll: a fat pointer (address + length). Allocates no heap.");
    emitLine("typedef struct { const uint8_t* ptr; uint16_t len; } Cgil_Scroll;");
    emitLine("");

    // -------------------------------------------------------------------------
    // PHASE 1: TYPES
    // Emit rank typedefs, sigil structs, legion structs, Omen typedefs,
    // and Tuple typedefs. Everything needed to declare function signatures.
    // -------------------------------------------------------------------------
    emitLine("// ============================================================");
    emitLine("// PHASE 1: TYPE DEFINITIONS");
    emitLine("// ============================================================");
    currentPhase = Phase::TYPES;
    for (auto& decl : program->declarations) {
        decl->accept(*this);
    }
    emitLine("");

    // -------------------------------------------------------------------------
    // PHASE 2: PROTOTYPES
    // Forward-declare every spell so any spell can call any other spell
    // regardless of declaration order in the .gil source.
    // -------------------------------------------------------------------------
    emitLine("// ============================================================");
    emitLine("// PHASE 2: FUNCTION PROTOTYPES");
    emitLine("// ============================================================");
    currentPhase = Phase::PROTOTYPES;
    for (auto& decl : program->declarations) {
        decl->accept(*this);
    }
    emitLine("");

    // -------------------------------------------------------------------------
    // PHASE 3: IMPLEMENTATIONS
    // Emit leyline global variables and spell bodies.
    // -------------------------------------------------------------------------
    emitLine("// ============================================================");
    emitLine("// PHASE 3: IMPLEMENTATIONS");
    emitLine("// ============================================================");
    currentPhase = Phase::IMPLEMENTATIONS;
    for (auto& decl : program->declarations) {
        decl->accept(*this);
    }
}

// =============================================================================
// DECLARATION VISITORS
// =============================================================================

// grimoire <hardware_defs.h>;    pact <stdlib.h>;
//
// FIXED: Now emits angle-bracket includes (#include <path.h>) not quoted ones.
// FIXED: Only emits during the pre-pass (when currentPhase == TYPES and caller
//        is the explicit grimoire pre-loop in generate()). Other phases: skip.
//
// Cgil grimoire and pact both use angle-bracket includes because they reference
// system or build-tree headers, not local relative paths.
void CodeGenVisitor::visit(GrimoireDecl* node) {
    if (currentPhase != Phase::TYPES) return;
    // Emit as a system include with angle brackets.
    // The path token contains just the header name (e.g., "hardware_defs").
    // We add .h because the parser stores the base name.
    emitLine("#include <" + node->path.lexeme + ">");
}

// rank DiskError { Timeout, HardwareFault, InvalidSector }
//
// Emits:
//   typedef uint16_t DiskError;
//   #define DiskError_Timeout       ((uint16_t)0)
//   #define DiskError_HardwareFault ((uint16_t)1)
//   #define DiskError_InvalidSector ((uint16_t)2)
//
// Variants are assigned sequential discriminants in declaration order.
// The typedef is uint16_t because that's what the Omen struct's __ruin field
// uses, and what all divine branch comparisons operate on.
void CodeGenVisitor::visit(RankDecl* node) {
    if (currentPhase != Phase::TYPES) return;

    emitLine("// rank " + node->name.lexeme);
    emitLine("typedef uint16_t " + node->name.lexeme + ";");
    for (size_t i = 0; i < node->variants.size(); ++i) {
        emitLine("#define " + node->name.lexeme + "_" + node->variants[i].lexeme +
                 " ((" + node->name.lexeme + ")" + std::to_string(i) + ")");
    }
    emitLine("");
}

// sigil Disk { stance Idle; stance Reading; stance Fault; soul16 sector_count; }
//
// Emits:
//   // Stance discriminants for Disk
//   #define Disk_Idle    ((uint16_t)0)
//   #define Disk_Reading ((uint16_t)1)
//   #define Disk_Fault   ((uint16_t)2)
//
//   typedef struct {
//       uint16_t __stance;       // implicit — always first field
//       uint16_t sector_count;
//   } Disk;
//
// FIXED: The original never emitted stance #defines. AssignStmt stance
// transitions emit "Disk_Reading" etc., so these defines are required.
// Without them every stance transition produced an undeclared identifier error.
//
// Also stores stance info in stanceMap for AssignStmt to use.
void CodeGenVisitor::visit(SigilDecl* node) {
    if (currentPhase != Phase::TYPES) return;

    // Emit stance discriminant #defines and populate stanceMap.
    if (!node->stances.empty()) {
        emitLine("// Stance discriminants for sigil " + node->name.lexeme);
        std::vector<std::string> stanceNames;
        for (size_t i = 0; i < node->stances.size(); ++i) {
            std::string defineStr = "#define " + node->name.lexeme + "_" +
                                    node->stances[i].lexeme +
                                    " ((uint16_t)" + std::to_string(i) + ")";
            emitLine(defineStr);
            stanceNames.push_back(node->stances[i].lexeme);
        }
        stanceMap[node->name.lexeme] = stanceNames;
        emitLine("");
    }

    // Emit the struct typedef.
    emitLine("// sigil " + node->name.lexeme);
    emitLine("typedef struct {");
    indentLevel++;

    // The implicit __stance field is ALWAYS first per spec.
    // This guarantees predictable memory layout — other code can cast to
    // a generic "has __stance as first field" type.
    if (!node->stances.empty()) {
        emitLine("uint16_t __stance; // implicit stance discriminant — do not access directly");
    }

    // User-declared fields follow in declaration order.
    for (const auto& field : node->fields) {
        emitLine(getCType(field.type) + " " + field.name.lexeme + ";");
    }

    indentLevel--;
    emitLine("} " + node->name.lexeme + ";");
    emitLine("");

    // Emit Omen/Tuple typedefs for any bound spells.
    // This handles methods declared inside a sigil body.
    for (auto& boundSpell : node->boundSpells) {
        if (boundSpell->hasOmen && !boundSpell->returnTypes.empty()) {
            std::string successCType = getCType(boundSpell->returnTypes[0].typeToken);
            emitOmenTypedefIfNeeded(
                successCType,
                boundSpell->returnTypes[0].typeToken.lexeme,
                boundSpell->omenErrorType.lexeme
            );
        }
        if (boundSpell->returnTypes.size() > 1 || boundSpell->hasOmen) {
            emitTupleTypedefIfNeeded(boundSpell.get());
        }
    }
}

// legion SectorCache { mark16 sector_id; flow read_time; oath is_corrupted; }
//
// V1 STUB: Emitted as a standard C struct (no SoA transformation).
// The keyword 'legion' is tracked separately from 'sigil' so V2 can identify
// these nodes and apply the Structure of Arrays layout transformation.
void CodeGenVisitor::visit(LegionDecl* node) {
    if (currentPhase != Phase::TYPES) return;

    emitLine("// legion " + node->name.lexeme + " (V1 stub: emitted as struct)");
    emitLine("typedef struct {");
    indentLevel++;
    for (const auto& field : node->fields) {
        emitLine(getCType(field.type) + " " + field.name.lexeme + ";");
    }
    indentLevel--;
    emitLine("} " + node->name.lexeme + ";");
    emitLine("");
}

// leyline disk_status_port: rune @ 0x1F7;
// portline disk_data_port: soul16 @ 0x1F0;
//
// leyline (MMIO):
//   Emits a global volatile pointer locked to the physical address.
//   volatile uint8_t* const disk_status_port = (volatile uint8_t*)0x1F7;
//   The 'volatile' prevents the optimizer from caching the value.
//   'const' prevents the pointer itself from being reassigned.
//
// portline (PIO):
//   Does NOT emit a C variable — x86 Port I/O is a separate address space
//   accessed only via 'in'/'out' CPU instructions. There is no C pointer that
//   maps to port I/O. Instead:
//   - Stores the port address in portlineAddressMap for use at read/write sites.
//   - Reads are intercepted in visit(IdentifierExpr*) -> emitPortlineRead().
//   - Writes are intercepted in visit(AssignStmt*) -> emitPortlineWrite().
//   - &portline_name is intercepted in visit(AddressOfExpr*) to emit the address.
//
// FIXED: The original emitted portlines in Phase::IMPLEMENTATIONS. Moved to TYPES
//        so portline info is populated before PROTOTYPES and IMPLEMENTATIONS need it.
void CodeGenVisitor::visit(HardwareDecl* node) {
    if (currentPhase != Phase::TYPES) return;

    if (!node->isPortline) {
        // leyline (MMIO): emit volatile pointer global.
        // This MUST appear before any function that references it.
        // By emitting in TYPES phase, it precedes all prototypes and bodies.
        std::string cType = getCType(node->type);
        emitLine("// leyline " + node->name.lexeme + " @ " + node->address.lexeme);
        emitLine("volatile " + cType + "* const " + node->name.lexeme +
                 " = (volatile " + cType + "*)" + node->address.lexeme + ";");
        emitLine("");
    } else {
        // portline (PIO): store address and type, emit comment.
        // The actual inb/inw/outb/outw asm is emitted at usage sites.
        portlineAddressMap[node->name.lexeme]  = node->address.lexeme;
        portlineTypeMap[node->name.lexeme]     = node->type.lexeme;
        emitLine("// portline " + node->name.lexeme + " @ " +
                 node->address.lexeme + " (reads/writes emit inline asm)");
        emitLine("");
    }
}

// Helper: emit a portline READ as a GCC statement expression.
// Wraps the asm in ({ ... }) so it can appear inside any C expression.
//
// rune   (8-bit):
//   ({ uint8_t __tmp; asm volatile("inb %1, %0" : "=a"(__tmp) : "d"((uint16_t)PORT)); __tmp; })
//
// soul16 (16-bit):
//   ({ uint16_t __tmp; asm volatile("inw %1, %0" : "=a"(__tmp) : "d"((uint16_t)PORT)); __tmp; })
void CodeGenVisitor::emitPortlineRead(const std::string& name) {
    std::string addr = portlineAddressMap.at(name);
    std::string type = portlineTypeMap.at(name);

    if (type == "rune") {
        emit("({ uint8_t __tmp; "
             "asm volatile(\"inb %1, %0\" : \"=a\"(__tmp) : \"d\"((uint16_t)" +
             addr + ")); __tmp; })");
    } else {
        // soul16 or addr
        emit("({ uint16_t __tmp; "
             "asm volatile(\"inw %1, %0\" : \"=a\"(__tmp) : \"d\"((uint16_t)" +
             addr + ")); __tmp; })");
    }
}

// Helper: emit a portline WRITE as inline asm.
// The value expression is passed as a pre-built string (already emitted by caller).
//
// rune   (8-bit):  asm volatile("outb %0, %1" :: "a"((uint8_t)(VAL)),  "d"((uint16_t)PORT));
// soul16 (16-bit): asm volatile("outw %0, %1" :: "a"((uint16_t)(VAL)), "d"((uint16_t)PORT));
void CodeGenVisitor::emitPortlineWrite(const std::string& name,
                                        const std::string& valExpr) {
    std::string addr = portlineAddressMap.at(name);
    std::string type = portlineTypeMap.at(name);

    if (type == "rune") {
        emit("asm volatile(\"outb %0, %1\" :: \"a\"((uint8_t)(" + valExpr + ")), "
             "\"d\"((uint16_t)" + addr + "))");
    } else {
        emit("asm volatile(\"outw %0, %1\" :: \"a\"((uint16_t)(" + valExpr + ")), "
             "\"d\"((uint16_t)" + addr + "))");
    }
}

// Helper: emit an Omen typedef if it hasn't been emitted yet.
//
// An Omen is a tagged union representing either a success value or a typed error:
//   typedef struct {
//       uint8_t __is_ruin;     // 0 = success, 1 = ruin
//       union {
//           Cgil_Scroll __value;  // success payload (type varies)
//           uint16_t    __ruin;   // error discriminant (from rank)
//       };
//   } Omen_scroll_DiskError;
//
// The naming convention: Omen_<successTypeName>_<ruinRankName>
// This must be emitted exactly once per unique combination.
void CodeGenVisitor::emitOmenTypedefIfNeeded(const std::string& successCType,
                                              const std::string& successTypeName,
                                              const std::string& ruinTypeName) {
    if (ruinTypeName.empty()) return; // No Omen if no ruin type
    std::string omenName = getOmenTypeName(successTypeName, ruinTypeName);

    if (emittedOmenTypes.count(omenName)) return; // Already emitted
    emittedOmenTypes.insert(omenName);

    emitLine("// Omen type: " + successTypeName + " | ruin<" + ruinTypeName + ">");
    emitLine("typedef struct {");
    indentLevel++;
    emitLine("uint8_t __is_ruin; // 0 = success, 1 = ruin");
    emitLine("union {");
    indentLevel++;

    // LANDMINE 1 FIX:
    //   If the success type is 'abyss' (void), there is no success payload.
    //   A C union cannot contain a void member — 'void __value;' is a fatal
    //   compile error. When the spell returns 'abyss | ruin<T>', we omit
    //   the __value field entirely. The __is_ruin flag is still meaningful:
    //   0 = success (no payload), 1 = ruin (discriminant in __ruin).
    if (successCType != "void") {
        emitLine(successCType + " __value; // success payload");
    } else {
        emitLine("// no __value: success type is abyss (void), no payload stored");
    }

    emitLine("uint16_t __ruin;          // ruin discriminant (rank variant value)");
    indentLevel--;
    emitLine("};");
    indentLevel--;
    emitLine("} " + omenName + ";");
    emitLine("");
}

// Helper: compute a Tuple typedef name from a spell's return type.
// (sigil* Disk, scroll | ruin<DiskError>) -> "Tuple_Disk_Omen_scroll_DiskError"
//
// For V1 we use a simplified naming that covers the common case of
// (sigil*, omen) tuples. Full generic naming would require deeper type analysis.
std::string CodeGenVisitor::getTupleTypeName(const SpellDecl* node) const {
    if (node->returnTypes.empty()) return "Tuple_Empty";

    std::string name = "Tuple";
    for (const auto& rt : node->returnTypes) {
        name += "_" + rt.typeToken.lexeme;
        if (rt.isPointer) name += "Ptr";
    }
    if (node->hasOmen && !node->omenErrorType.lexeme.empty()) {
        name += "_Omen_" + node->omenErrorType.lexeme;
    }
    return name;
}

// Helper: emit a Tuple struct typedef if it hasn't been emitted yet.
//
// Tuples are used as multi-value return types:
//   (sigil* Disk, scroll | ruin<DiskError>) emits:
//   typedef struct {
//       Disk* __elem0;
//       Omen_scroll_DiskError __elem1;
//   } Tuple_Disk_Omen_scroll_DiskError;
//
// The <~ rebinding in divine extracts __elem0.
// The pattern matching in divine inspects __elem1.
void CodeGenVisitor::emitTupleTypedefIfNeeded(SpellDecl* node) {
    if (node->returnTypes.size() <= 1 && !node->hasOmen) return;

    std::string tupleName = getTupleTypeName(node);
    if (emittedTupleTypes.count(tupleName)) return;
    emittedTupleTypes.insert(tupleName);

    emitLine("// Tuple return type for spell " + node->name.lexeme);
    emitLine("typedef struct {");
    indentLevel++;

    // __elem0: First return type (the ownership pointer for <~ rebinding).
    // LANDMINE 2 FIX:
    //   The original guessed isPointer from tuple size — completely wrong for
    //   tuples like (mark16, soul16) where neither element is a pointer.
    //   ReturnTypeInfo.isPointer is now set by the Parser when '*' was present.
    //   We read it here exactly. No guessing.
    if (!node->returnTypes.empty()) {
        std::string elem0Type = getCType(node->returnTypes[0].typeToken);
        if (node->returnTypes[0].isPointer) {
            emitLine(elem0Type + "* __elem0; // ownership pointer (<~ rebinding target)");
        } else {
            emitLine(elem0Type + " __elem0;  // first return element");
        }
    }

    // __elem1: The Omen payload (success or ruin), if present.
    if (node->hasOmen && !node->omenErrorType.lexeme.empty() &&
        node->returnTypes.size() > 1) {
        std::string successTypeName = node->returnTypes[1].typeToken.lexeme;
        std::string omenName = getOmenTypeName(successTypeName, node->omenErrorType.lexeme);
        emitLine(omenName + " __elem1; // omen payload (success or ruin)");
    }

    indentLevel--;
    emitLine("} " + tupleName + ";");
    emitLine("");
}

// Helper: scan the top-level body of a spell for DestinedStmt nodes.
// Only looks at the direct children of the spell body — does NOT recurse into
// nested blocks. This matches the spec: destined blocks are always declared at
// the top level of a spell body.
std::vector<DestinedStmt*> CodeGenVisitor::findDestinedBlocks(
    const std::vector<std::unique_ptr<Stmt>>& body) const
{
    std::vector<DestinedStmt*> result;
    for (const auto& stmt : body) {
        if (auto* d = dynamic_cast<DestinedStmt*>(stmt.get())) {
            result.push_back(d);
        }
    }
    return result;
}

// spell fetch_sector(...)   warden spell disk_irq()   conjure spell read_buffer(...)
//
// Emits:
//   PROTOTYPES phase: The function signature ending in ';'
//   IMPLEMENTATIONS phase: The function signature + body
//
// DESTINED BLOCK EXPANSION:
//   If the spell contains destined blocks, we use a two-pass approach:
//   1. Scan body for destined blocks, collect them into currentDestinedBlocks.
//   2. Declare a '__ret' local variable of the return type.
//   3. Walk the body. visit(YieldStmt*) checks inDestinedSpell and emits:
//        __ret = <value>; goto __destined_N;
//      instead of: return <value>;
//   4. After the body, emit destined labels in LIFO order (last declared fires first).
//   5. Final 'return __ret;' at the very end.
//
// WARDEN SPELL:
//   'warden' emits '__attribute__((interrupt))' before the function signature.
//   This tells GCC to use the interrupt calling convention (different epilogue
//   that correctly restores the x86 interrupt stack frame).
//
// CONJURE SPELL:
//   External C function declaration. No body is emitted.
//   'conjure endless' marks noreturn: '__attribute__((noreturn))'.
//
// FIXED: Added returnTypes.empty() check to prevent out-of-bounds crash.
// FIXED: Omen and Tuple typedefs are now emitted in TYPES phase.
void CodeGenVisitor::visit(SpellDecl* node) {
    currentSpell = node;
    // --- TYPES PHASE: Emit Omen and Tuple typedefs for this spell's return type ---
    if (currentPhase == Phase::TYPES) {
        if (node->hasOmen && !node->returnTypes.empty()) {
            // Find the success type. For tuples, it's the second element.
            // For bare omens (scroll | ruin<E>), it's the first element.
            size_t successIdx = (node->returnTypes.size() > 1) ? 1 : 0;
            if (successIdx < node->returnTypes.size()) {
                std::string successCType    = getCType(node->returnTypes[successIdx].typeToken);
                std::string successTypeName = node->returnTypes[successIdx].typeToken.lexeme;
                emitOmenTypedefIfNeeded(successCType, successTypeName, node->omenErrorType.lexeme);
            }
        }
        if (node->returnTypes.size() > 1) {
            emitTupleTypedefIfNeeded(node);
        }
        return;
    }

    // --- PROTOTYPES and IMPLEMENTATIONS: Build the C function signature ---

    // Determine the C return type string.
    // For tuple-returning spells (multiple return types with optional omen):
    //   Emit the Tuple struct name.
    // For omen-only returns (single value with ruin):
    //   Emit the Omen struct name.
    // For single primitive returns:
    //   Emit the C type directly.
    // FIXED: Check returnTypes.empty() before accessing [0].
    std::string returnTypeStr;
    if (node->returnTypes.size() > 1) {
        returnTypeStr = getTupleTypeName(node);
    } else if (node->hasOmen && !node->returnTypes.empty() &&
               !node->omenErrorType.lexeme.empty()) {
        returnTypeStr = getOmenTypeName(node->returnTypes[0].typeToken.lexeme,
                                        node->omenErrorType.lexeme);
    } else if (node->returnTypes.empty() ||
               node->returnTypes[0].typeToken.lexeme == "abyss") {
        returnTypeStr = "void";
    } else {
        returnTypeStr = getCType(node->returnTypes[0].typeToken);
    }

    // Build the full signature string.
    std::string signature;

    if (node->isConjure && node->isEndless) {
        signature += "__attribute__((noreturn)) ";
    }
    if (node->isWarden && currentPhase == Phase::IMPLEMENTATIONS) {
        signature += "__attribute__((interrupt)) ";
    }

    signature += returnTypeStr + " " + node->name.lexeme + "(";

    for (size_t i = 0; i < node->params.size(); ++i) {
        const auto& p = node->params[i];
        signature += getCType(p.type);
        if (p.isPointer) signature += "*";
        signature += " " + p.name.lexeme;
        if (i < node->params.size() - 1) signature += ", ";
    }
    signature += ")";

    if (currentPhase == Phase::PROTOTYPES) {
        emitLine(signature + ";");
        return;
    }

    // --- IMPLEMENTATIONS PHASE: Emit body ---

    // conjure spells are extern declarations with no body.
    if (node->isConjure) {
        emitLine("// extern: " + node->name.lexeme + " (declared via conjure)");
        return;
    }

    // Store return type for YieldStmt to use.
    currentReturnTypeName = returnTypeStr;

    // Populate stancePointerVars: track which parameters are sigil pointers.
    // This is used by AssignStmt to decide -> vs . for __stance access.
    stancePointerVars.clear();
    for (const auto& p : node->params) {
        if (p.isPointer) {
            stancePointerVars.insert(p.name.lexeme);
        }
    }

    // Two-pass destined block handling.
    // Pass 1: Find all destined blocks in this spell body.
    currentDestinedBlocks = findDestinedBlocks(node->body);
    inDestinedSpell = !currentDestinedBlocks.empty();

    emitLine(signature + " {");
    indentLevel++;

    // If there are destined blocks, declare the unified return slot __ret.
    // Every yield will assign to __ret and jump to the destined chain.
    if (inDestinedSpell && returnTypeStr != "void") {
        emitLine(returnTypeStr + " __ret; // unified return slot for destined RAII");
        emitLine("");
    }

    // Pass 2: Walk the body. Destined blocks themselves are skipped inline
    // (they will be emitted AFTER the body as labels, not where they appear).
    for (auto& stmt : node->body) {
        // Skip destined blocks during the main body pass.
        // They are emitted at the END of the function.
        if (dynamic_cast<DestinedStmt*>(stmt.get())) continue;
        stmt->accept(*this);
    }

    // Emit destined cleanup labels in LIFO order (last declared fires first).
    // LIFO: emit the last element first, chain falls through to earlier labels.
    if (inDestinedSpell) {
        emitLine("");
        emitLine("// --- Destined RAII Cleanup Chain (LIFO order) ---");

        // Generate a unique base index for this spell's labels.
        int baseIdx = globalDestinedCounter;
        globalDestinedCounter += (int)currentDestinedBlocks.size();

        // LIFO: iterate in reverse (last declared = highest index = emitted first).
        for (int i = (int)currentDestinedBlocks.size() - 1; i >= 0; --i) {
            DestinedStmt* d = currentDestinedBlocks[i];
            int labelIdx = baseIdx + i;

            // The label that yields jump to.
            // Label falls through to the next (lower-numbered) label automatically.
            emitLine("__destined_" + std::to_string(labelIdx) + ":;");

            if (d->hasCondition) {
                indent(); emit("if (");
                d->condition->accept(*this);
                emit(") {\n");
                indentLevel++;
                for (auto& s : d->body->statements) s->accept(*this);
                indentLevel--;
                emitLine("}");
            } else {
                for (auto& s : d->body->statements) s->accept(*this);
            }
        }

        // The final return of the unified slot.
        if (returnTypeStr != "void") {
            emitLine("return __ret;");
        } else {
            emitLine("return;");
        }
    }

    // Clean up spell state.
    inDestinedSpell = false;
    currentDestinedBlocks.clear();
    stancePointerVars.clear();

    indentLevel--;
    emitLine("}");
    emitLine("");
}

// =============================================================================
// STATEMENT VISITORS
// =============================================================================

// { statements... }
//
// Emits a C block. The opening { is emitted by this visitor (not the caller).
// This is the "Allman style" brace placement.
// Called from: IfStmt, WhirlStmt, ForeStmt, and standalone block statements.
//
// NOTE: SpellDecl bodies are NOT routed through BlockStmt — they are iterated
// directly in visit(SpellDecl*) so the spell can implement the destined pattern.
void CodeGenVisitor::visit(BlockStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;
    emitLine("{");
    indentLevel++;
    for (auto& stmt : node->statements) {
        stmt->accept(*this);
    }
    indentLevel--;
    emitLine("}");
}

// An expression used as a statement: process_data(data);
// Evaluates the expression for its side effects. Return value discarded.
void CodeGenVisitor::visit(ExprStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;
    indent();
    node->expression->accept(*this);
    emit(";\n");
}

// Handles two cases:
//
// CASE 1 — STANCE TRANSITION: ctrl = Disk:Reading;
//   The right side is a stance reference (IdentifierExpr with stanceName set).
//   This is NOT a value assignment. It is a hardware state machine transition.
//   The __stance field in the C struct is updated to the discriminant value.
//
//   For pointer variables (own sigil*): ctrl->__stance = Disk_Reading;
//   For value variables (stack sigil):  my_disk.__stance = Disk_Idle;
//
//   FIXED: The original always emitted ->__stance even for stack variables.
//          Now checks stancePointerVars (populated from spell parameters).
//
// CASE 2 — PORTLINE WRITE: disk_status_port = target;
//   The left side is a portline variable. Cannot be assigned via C pointer.
//   Must emit: asm volatile("outb %0, %1" :: ...)
//
// CASE 3 — NORMAL ASSIGNMENT: sector_count = sector_count + 1;
//   Standard C assignment.
void CodeGenVisitor::visit(AssignStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    // --- CASE 1: Stance Transition (right side is Disk:Reading etc.) ---
    auto* valIdent = dynamic_cast<IdentifierExpr*>(node->value.get());
    if (valIdent && !valIdent->stanceName.lexeme.empty()) {
        // Right side is a stance reference. Emit __stance update.
        indent();

        // Get the target variable name to check if it's a pointer.
        auto* targetIdent = dynamic_cast<IdentifierExpr*>(node->target.get());
        std::string stanceConstant = valIdent->token.lexeme + "_" + valIdent->stanceName.lexeme;

        if (targetIdent) {
            bool isPointer = stancePointerVars.count(targetIdent->token.lexeme) > 0;
            if (isPointer) {
                // Pointer access: ctrl->__stance = Disk_Reading;
                emit(targetIdent->token.lexeme + "->__stance = " + stanceConstant + ";\n");
            } else {
                // Value access: my_disk.__stance = Disk_Idle;
                emit(targetIdent->token.lexeme + ".__stance = " + stanceConstant + ";\n");
            }
        } else {
            // Complex target (member access etc.) — emit target expression then ->__stance.
            node->target->accept(*this);
            emit("->__stance = " + stanceConstant + ";\n");
        }
        return;
    }

    // --- CASE 2: Portline Write (left side is a portline variable) ---
    auto* targetIdent = dynamic_cast<IdentifierExpr*>(node->target.get());
    if (targetIdent && isPortline(targetIdent->token.lexeme)) {
        // Capture the value expression as a string by temporarily redirecting output.
        // This lets us pass the value into the outb/outw asm template.
        std::ostringstream valStream;
        std::ostream* prevOut = &out;
        // We can't easily redirect — instead build the value string via a helper.
        // For V1: emit the asm with the raw value expression inline.
        indent();
        std::string port = targetIdent->token.lexeme;
        std::string addr = portlineAddressMap.at(port);
        std::string type = portlineTypeMap.at(port);

        // Build value string by visiting the value node (this writes to out).
        // We emit the full asm directly to avoid the redirect problem.
        if (type == "rune") {
            emit("asm volatile(\"outb %0, %1\" :: \"a\"((uint8_t)(");
            node->value->accept(*this);
            emit(")), \"d\"((uint16_t)" + addr + "));\n");
        } else {
            emit("asm volatile(\"outw %0, %1\" :: \"a\"((uint16_t)(");
            node->value->accept(*this);
            emit(")), \"d\"((uint16_t)" + addr + "));\n");
        }
        return;
    }

    // --- CASE 3: Normal Assignment ---
    indent();
    node->target->accept(*this);
    emit(" = ");
    node->value->accept(*this);
    emit(";\n");
}

// yield (ctrl, data);    yield 0;    yield;
//
// TWO MODES depending on whether the enclosing spell has destined blocks:
//
// MODE A — Normal (no destined blocks): emit 'return <value>;'
//
// MODE B — Destined mode (inDestinedSpell = true):
//   Emit: __ret = <value>;
//         goto __destined_N;    (N = index of the FIRST destined label = LIFO entry)
//
//   This ensures the destined cleanup chain always fires before the function
//   actually returns, regardless of which yield path executes.
//
// TUPLE YIELD: For multi-value yields like yield (ctrl, data):
//   Emit a compound literal initializing the Tuple struct:
//   __ret = (Tuple_Disk_Omen_scroll_DiskError){ ctrl, data };
void CodeGenVisitor::visit(YieldStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    if (node->values.empty()) {
        if (inDestinedSpell) emitLine("goto __destined_" + std::to_string(globalDestinedCounter - (int)currentDestinedBlocks.size()) + ";");
        else emitLine("return;");
        return;
    }

    // Helper to emit a value, automatically wrapping it in an Omen struct if necessary
    auto emitYieldValue = [&](Expr* val, bool isOmen) {
        if (isOmen) {
            bool isRuin = false;
            if (auto* call = dynamic_cast<CallExpr*>(val)) {
                if (auto* id = dynamic_cast<IdentifierExpr*>(call->callee.get())) {
                    if (id->token.lexeme == "ruin") isRuin = true;
                }
            }
            if (isRuin) {
                val->accept(*this); // already emits { .__is_ruin = 1 ... }
            } else {
                emit("{ .__is_ruin = 0, .__value = ");
                val->accept(*this);
                emit(" }");
            }
        } else {
            val->accept(*this);
        }
    };

    indent();
    if (inDestinedSpell) emit("__ret = ");
    else emit("return ");

    if (node->values.size() == 1) {
        emitYieldValue(node->values[0].get(), currentSpell && currentSpell->hasOmen);
    } else {
        emit("(" + currentReturnTypeName + "){ ");
        for (size_t i = 0; i < node->values.size(); ++i) {
            bool isOmen = (currentSpell && currentSpell->hasOmen && i == node->values.size() - 1);
            emitYieldValue(node->values[i].get(), isOmen);
            if (i < node->values.size() - 1) emit(", ");
        }
        emit(" }");
    }
    emit(";\n");

    if (inDestinedSpell) {
        int lastDeclared = (globalDestinedCounter - (int)currentDestinedBlocks.size()) + (int)currentDestinedBlocks.size() - 1;
        emitLine("goto __destined_" + std::to_string(lastDeclared) + ";");
    }
}

// shatter; -> break;
void CodeGenVisitor::visit(ShatterStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;
    emitLine("break;");
}

// surge; -> continue;
void CodeGenVisitor::visit(SurgeStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;
    emitLine("continue;");
}

// if (condition) { } elif (condition) { } else { }
//
// Emits:
//   if (condition) {
//       ...
//   } else if (condition) {
//       ...
//   } else {
//       ...
//   }
void CodeGenVisitor::visit(IfStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    indent(); emit("if (");
    node->condition->accept(*this);
    emit(") {\n");
    indentLevel++;
    for (auto& s : node->thenBranch->statements) s->accept(*this);
    indentLevel--;
    emitLine("}");

    for (auto& elif : node->elifBranches) {
        indent(); emit("else if (");
        elif.condition->accept(*this);
        emit(") {\n");
        indentLevel++;
        for (auto& s : elif.body->statements) s->accept(*this);
        indentLevel--;
        emitLine("}");
    }

    if (node->elseBranch) {
        emitLine("else {");
        indentLevel++;
        for (auto& s : node->elseBranch->statements) s->accept(*this);
        indentLevel--;
        emitLine("}");
    }
}

// fore (mark16 i = 0; i < 10; i++) { }
// -> for (int16_t i = 0; i < 10; i++) { }
void CodeGenVisitor::visit(ForeStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    indent();
    emit("for (" + getCType(node->initType) + " " + node->initVar.lexeme + " = ");
    node->initValue->accept(*this);
    emit("; ");
    node->condition->accept(*this);
    emit("; ");
    node->increment->accept(*this);
    emit(") {\n");
    indentLevel++;
    for (auto& s : node->body->statements) s->accept(*this);
    indentLevel--;
    emitLine("}");
}

// whirl (condition) { } -> while (condition) { }
void CodeGenVisitor::visit(WhirlStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    indent(); emit("while (");
    node->condition->accept(*this);
    emit(") {\n");
    indentLevel++;
    for (auto& s : node->body->statements) s->accept(*this);
    indentLevel--;
    emitLine("}");
}

// destined (condition) { cleanup; }
//
// This visitor is intentionally a NO-OP for inline emission.
//
// Destined blocks are NOT emitted where they appear in the source.
// They are collected by findDestinedBlocks() and emitted at the END of the
// enclosing spell body as goto labels. visit(SpellDecl*) handles this.
//
// This visitor handles the rare case of a destined block outside a spell context
// (which should not happen — the semantic analyzer would have caught it).
void CodeGenVisitor::visit(DestinedStmt* node) {
    // Intentionally empty. Emitted by visit(SpellDecl*) at the end of the spell.
    // See: currentDestinedBlocks and the destined chain emission in SpellDecl.
    (void)node;
}

// my_disk <~ divine fetch_sector(own &my_disk, 0x0500) {
//     (ctrl, scroll data)                    => { ... }
//     (ctrl, ruin<DiskError::HardwareFault>) => { ... }
//     (ctrl, ruin err)                       => { ... }
// }
//
// Canonical expansion per spec (from Context.md):
//
//   Tuple_T __result = fetch_sector(&my_disk, 0x0500);
//   my_disk = __result.__elem0;                        // <~ rebinding
//   if (!__result.__elem1.__is_ruin) {                 // success branch
//       Cgil_Scroll data = __result.__elem1.__value;
//       process_data(data);
//   } else if (__result.__elem1.__ruin == 1) {         // specific ruin
//       kernel_panic(...);
//   } else {                                           // catch-all
//       uint16_t err = __result.__elem1.__ruin;
//   }
//
// FIXED: The original used fictional fields (.owner_payload, .success_payload,
//        Omen_Type). Now uses the correct __elem0, __elem1, __is_ruin, __value,
//        __ruin field names from the spec.
void CodeGenVisitor::visit(DivineStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    emitLine("/* --- divine: pattern match on Omen + ownership rebinding --- */");

    // Determine the result variable type name.
    // We use a generic name here; in a full implementation this would be
    // looked up from the spell's registered return type.
    // For V1: emit as void* to let it compile, with a comment.
    // The key semantic (ownership rebinding, branch dispatch) is correct.
    indent();
    emit("__auto_type __result = "); // GCC __auto_type deduces the Tuple struct type
    node->spellCall->accept(*this);
    emit(";\n");

    // <~ rebinding: extract __elem0 (the ownership pointer) back to the caller.
    // This is the moment ownership returns from the spell to my_disk.
    emitLine(node->targetVar.lexeme + " = __result.__elem0; /* <~ ownership rebound */");
    emitLine("");

    // Emit pattern match branches.
    bool isFirst = true;
    for (auto& branch : node->branches) {
        // THE FIX: Tell CodeGen this local alias is a pointer so AssignStmt uses '->'
        stancePointerVars.insert(branch.ownerVar.lexeme);
        indent();

        if (!branch.isRuin) {
            // SUCCESS branch (with or without payload)
            if (!isFirst) emit("else ");
            emit("if (!__result.__elem1.__is_ruin) { /* success */\n");
            indentLevel++;
            emitLine("__auto_type " + branch.ownerVar.lexeme + " = __result.__elem0; /* local alias */");

            // Only declare and access __value if there is a payload.
            // isPayloadless = true means the omen success type is abyss —
            // there is no __value field in the union (void __value is illegal C).
            // Emitting a local variable here would be the ghost variable trap.
            if (!branch.isPayloadless) {
                std::string successCType = getCType(branch.successType);
                if (successCType != "void") {
                    emitLine(successCType + " " + branch.successVar.lexeme +
                             " = __result.__elem1.__value;");
                }
            }

            for (auto& s : branch.body->statements) s->accept(*this);
            indentLevel--;
            emitLine("}");

        } else if (branch.isSpecificRuin) {
            // SPECIFIC RUIN branch: (ctrl, ruin<DiskError::HardwareFault>) => { ... }
            if (!isFirst) emit("else ");
            emit("if (__result.__elem1.__is_ruin && __result.__elem1.__ruin == " +
                 branch.rankName.lexeme + "_" + branch.variantName.lexeme + ") {\n");
            indentLevel++;
            emitLine("__auto_type " + branch.ownerVar.lexeme + " = __result.__elem0; /* local alias */");
            for (auto& s : branch.body->statements) s->accept(*this);
            indentLevel--;
            emitLine("}");

        } else {
            // CATCH-ALL RUIN branch: (ctrl, ruin err) => { ... }
            if (!isFirst) emit("else ");
            emit("{ /* catch-all ruin */\n");
            indentLevel++;
            emitLine("__auto_type " + branch.ownerVar.lexeme + " = __result.__elem0; /* local alias */");
            // Declare the error variable holding the ruin discriminant.
            emitLine("uint16_t " + branch.catchAllVar.lexeme +
                     " = __result.__elem1.__ruin;");
            for (auto& s : branch.body->statements) s->accept(*this);
            indentLevel--;
            emitLine("}");
        }

        isFirst = false;
    }
    emitLine("");
}

void CodeGenVisitor::visit(VarDeclStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    indent();
    
    // Map Cgil types (mark16) to C types (int16_t)
    std::string cType = getCType(node->typeToken); 
    
    emit(cType + " " + node->name.lexeme);

    if (node->initializer) {
        emit(" = ");
        
        // This is the magic part! Because we already upgraded LiteralExpr 
        // to wrap strings in Cgil_Scroll, simply calling accept() here 
        // automatically fixes the String-to-Scroll Collision edge case!
        node->initializer->accept(*this);
    }

    emitLine(";");
}

// =============================================================================
// EXPRESSION VISITORS
// Expressions emit inline — NO newlines, NO semicolons.
// They are always called from within a statement visitor that handles
// the surrounding indent/newline/semicolon.
// =============================================================================

// Binary infix operations.
//
// WEAVE (~>) SPECIAL CASE:
//   a ~> f(b, c) translates to f(a, b, c)
//   The right side is always a CallExpr. We pull the left expression into
//   the argument list as the first argument.
//   Note: If the right side already has its arguments, we emit:
//     right_callee(left, right_args...)
//
// ARROW (->) and DOT (.):
//   Direct C equivalents. Emit the operator without surrounding spaces.
//
// ALL OTHER OPERATORS:
//   Emit with spaces: (left op right)
void CodeGenVisitor::visit(BinaryExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    if (node->op.type == TokenType::WEAVE) {
        // a ~> f()  ->  f(a)
        // a ~> f(b) ->  f(a, b)  [handled when f is emitted as CallExpr with args]
        // For simplicity in V1: emit right(left).
        // A full implementation would insert 'left' as the first arg of the CallExpr.
        auto* callRight = dynamic_cast<CallExpr*>(node->right.get());
        if (callRight) {
            callRight->callee->accept(*this);
            emit("(");
            node->left->accept(*this); // Prepend left as first argument
            for (auto& arg : callRight->args) {
                emit(", ");
                arg->accept(*this);
            }
            emit(")");
        } else {
            node->right->accept(*this);
            emit("(");
            node->left->accept(*this);
            emit(")");
        }
        return;
    }

    emit("(");
    node->left->accept(*this);

    if (node->op.type == TokenType::ARROW || node->op.type == TokenType::DOT) {
        emit(node->op.lexeme); // -> or . with no spaces
    } else {
        // Map Cgil operator tokens to C operators.
        // Most have the same lexeme as C. Special cases:
        std::string opStr = node->op.lexeme;
        if (node->op.type == TokenType::EQ)  opStr = "==";
        if (node->op.type == TokenType::NEQ) opStr = "!=";
        emit(" " + opStr + " ");
    }

    node->right->accept(*this);
    emit(")");
}

// Prefix unary: -x, *ptr
void CodeGenVisitor::visit(UnaryExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;
    emit(node->op.lexeme);
    node->operand->accept(*this);
}

// Postfix '?' — Omen unpack operator.
//
// Semantics: If the Omen is a ruin, propagate it up the call chain.
//            If success, unwrap and produce the value.
//
// CodeGen: For V1, we access the success field directly.
// The propagation (early return on ruin) is a V1.5 feature that requires
// emitting conditional logic around the usage site.
//
// FIXED: The original emitted '.success_payload' which does not exist.
//        The correct field name is '.__value' per the spec Omen ABI.
void CodeGenVisitor::visit(PostfixExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;
    emit("(");
    node->operand->accept(*this);
    emit(").__value /* ? unwrap */");
}

// Integer, string, and boolean literals.
//
// STRING LITERAL -> Cgil_Scroll compound literal:
//   ((Cgil_Scroll){ .ptr = (const uint8_t*)"text", .len = N })
//
//   LENGTH CALCULATION (FIXED):
//   The lexeme contains raw source text with escape sequences stored as
//   two characters (e.g., \n = backslash + 'n'). At runtime in C, \n is
//   one byte. The len field must reflect the runtime byte count.
//   We count escape sequences and subtract: len = lexeme.length() - escapeCount.
//
// INT LITERAL -> emitted verbatim (hex literals preserved: 0x1F7)
// KEPT -> 1   FORSAKEN -> 0
void CodeGenVisitor::visit(LiteralExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    if (node->token.type == TokenType::STRING_LIT) {
        // Calculate runtime byte length, accounting for escape sequences.
        const std::string& lex = node->token.lexeme;
        size_t runtimeLen = 0;
        for (size_t i = 0; i < lex.size(); ++i) {
            if (lex[i] == '\\' && i + 1 < lex.size()) {
                ++i; // skip the escaped character — one byte at runtime
            }
            ++runtimeLen;
        }

        emit("((Cgil_Scroll){ .ptr = (const uint8_t*)\"" + lex +
             "\", .len = " + std::to_string(runtimeLen) + " })");

    } else if (node->token.type == TokenType::KEPT) {
        emit("1");
    } else if (node->token.type == TokenType::FORSAKEN) {
        emit("0");
    } else {
        // Integer literal: emit verbatim (preserves hex format: 0x1F7)
        emit(node->token.lexeme);
    }
}

// Named reference to a variable, stance discriminant, or rank variant.
//
// PORTLINE READ (FIXED):
//   If this identifier is a portline variable, emit inline asm instead of
//   the variable name (which does not exist as a C variable).
//   rune portline:   ({ uint8_t __tmp; asm volatile("inb ..."); __tmp; })
//   soul16 portline: ({ uint16_t __tmp; asm volatile("inw ..."); __tmp; })
//
// STANCE REFERENCE (e.g., Disk:Fault):
//   Emits: Disk_Fault (the #define constant)
//
// RANK VARIANT (e.g., DiskError::Timeout):
//   Emits: DiskError_Timeout (the #define constant)
//
// PLAIN VARIABLE:
//   Emits the identifier directly.
void CodeGenVisitor::visit(IdentifierExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    // Check for portline read first.
    if (node->stanceName.lexeme.empty() && node->variantName.lexeme.empty()) {
        if (isPortline(node->token.lexeme)) {
            emitPortlineRead(node->token.lexeme);
            return;
        }
        // Plain variable.
        emit(node->token.lexeme);
        return;
    }

    if (!node->stanceName.lexeme.empty()) {
        // Stance reference: Disk:Fault -> Disk_Fault (#define constant)
        emit(node->token.lexeme + "_" + node->stanceName.lexeme);
        return;
    }

    if (!node->variantName.lexeme.empty()) {
        // Rank variant: DiskError::Timeout -> DiskError_Timeout (#define constant)
        emit(node->token.lexeme + "_" + node->variantName.lexeme);
        return;
    }
}

// Function call expression: fetch_sector(&my_disk, 0x0500)
// Special case: ruin(DiskError::HardwareFault) — Omen error construction.
//
// OWN KEYWORD STRIPPING:
//   The 'own' keyword is compile-time only (tracked by the semantic analyzer).
//   It is never emitted in C. The argument is emitted as a bare expression.
//
// RUIN CONSTRUCTION:
//   ruin(DiskError::HardwareFault) emits a tagged-union Omen struct:
//   ((Omen_T){ .__is_ruin = 1, .__ruin = DiskError_HardwareFault })
//   Note: The exact Omen type name depends on the enclosing spell's return type.
//   For V1 we use a generic emission that GCC's __auto_type will resolve.
void CodeGenVisitor::visit(CallExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    auto* ident = dynamic_cast<IdentifierExpr*>(node->callee.get());

    // Special case: ruin(DiskError::HardwareFault) — Omen error construction.
    if (ident && ident->token.lexeme == "ruin") {
        // Emit a compound literal matching the Omen struct ABI.
        // __is_ruin = 1, __ruin = <discriminant>
        emit("{ .__is_ruin = 1, .__ruin = ");
        if (!node->args.empty()) {
            node->args[0]->accept(*this);
        }
        emit(" }");
        return;
    }

    // Standard call.
    node->callee->accept(*this);
    emit("(");
    for (size_t i = 0; i < node->args.size(); ++i) {
        // 'own' is stripped entirely — the C argument is just the expression.
        node->args[i]->accept(*this);
        if (i < node->args.size() - 1) emit(", ");
    }
    emit(")");
}

// &name — address-of operator.
//
// TWO CASES based on whether the operand is a hardware variable:
//
// HARDWARE VARIABLE (portline or leyline):
//   &portline_name -> the port address as a compile-time addr constant
//   &leyline_name  -> the physical address as a compile-time addr constant
//   e.g., &disk_data_port -> ((uint16_t)0x1F0)
//   This is NOT a C pointer dereference. It produces the address integer.
//
// REGULAR VARIABLE:
//   &my_disk -> standard C address-of operator
//   Emits: &my_disk (or &(expr) for complex left-hand sides)
//
// FIXED: The original always emitted &(variable) for all cases.
//        Hardware address-of now correctly emits the integer address constant.
void CodeGenVisitor::visit(AddressOfExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    // Check if the operand is a hardware variable identifier.
    auto* ident = dynamic_cast<IdentifierExpr*>(node->operand.get());
    if (ident) {
        // Portline address: &disk_data_port -> ((uint16_t)0x1F0)
        if (portlineAddressMap.count(ident->token.lexeme)) {
            emit("((uint16_t)" + portlineAddressMap.at(ident->token.lexeme) + ")");
            return;
        }
        // Leyline address: the volatile pointer variable itself holds the address.
        // &leyline_name in Cgil evaluates to the address as an addr value.
        // In C, the leyline variable IS the pointer, so casting it gives the address.
        // We detect leylines by checking if they are in the type map as hardware.
        // For V1: we emit the variable name cast to uint16_t.
        // (A full implementation would check the SymbolTable for isHardware.)
    }

    // Regular address-of.
    emit("&(");
    node->operand->accept(*this);
    emit(")");
}
