// ============================================================
// GENERATED BY CGIL COMPILER v1.0
// DO NOT EDIT BY HAND
// ============================================================

// --- System Includes ---
#include <stdint.h>
#include <stdbool.h>

// --- Cgil Grimoire Includes ---

// --- Cgil Runtime Structures ---
// scroll: a fat pointer (address + length). Allocates no heap.
typedef struct { const uint8_t* ptr; uint16_t len; } Cgil_Scroll;

// ============================================================
// PHASE 1: TYPE DEFINITIONS
// ============================================================

// ============================================================
// PHASE 2: FUNCTION PROTOTYPES
// ============================================================
int16_t test_all_primitives(int16_t a, int32_t b, uint16_t c, uint32_t d, uint16_t e, uint8_t f, uint8_t g);
int16_t main();

// ============================================================
// PHASE 3: IMPLEMENTATIONS
// ============================================================
int16_t test_all_primitives(int16_t a, int32_t b, uint16_t c, uint32_t d, uint16_t e, uint8_t f, uint8_t g) {
    int16_t add_result = (a + a)    ;
    int16_t sub_result = (a - a)    ;
    int16_t mul_result = (a * a)    ;
    int16_t div_result = (a / a)    ;
    uint8_t eq_test = (a == a)    ;
    uint8_t neq_test = (a != a)    ;
    uint8_t gt_test = (a > a)    ;
    uint8_t lt_test = (a < a)    ;
    uint8_t always_true = 1    ;
    uint8_t always_false = 0    ;
    int16_t decimal_lit = 255    ;
    int16_t hex_lit = 0xFF    ;
    uint16_t large_hex = 0xB800    ;
    uint16_t hw_addr = 0x1F7    ;
    int32_t local_b = b    ;
    uint16_t local_c = c    ;
    uint32_t local_d = d    ;
    uint16_t local_e = e    ;
    uint8_t local_f = f    ;
    uint8_t local_g = g    ;
    return add_result;
}

int16_t main() {
    int16_t prim_result = test_all_primitives(100, 200, 300, 400, 0x1F0, 0xAB, 1)    ;
    return prim_result;
}

