// ============================================================
// GENERATED BY CGIL COMPILER v1.0
// DO NOT EDIT BY HAND
// ============================================================

// --- System Includes ---
#include <stdint.h>
#include <stdbool.h>

// --- Cgil Grimoire Includes ---
#include <stdio.h>

// --- Cgil Runtime Structures ---
// scroll: a fat pointer (address + length). Allocates no heap.
typedef struct { const uint8_t* ptr; uint16_t len; } Cgil_Scroll;

// ============================================================
// PHASE 1: TYPE DEFINITIONS
// ============================================================
#include <stdio.h>

// ============================================================
// PHASE 2: FUNCTION PROTOTYPES
// ============================================================
int32_t putchar(int32_t character);
int32_t main();

// ============================================================
// PHASE 3: IMPLEMENTATIONS
// ============================================================
// extern: putchar (declared via conjure)
int32_t main() {
    putchar(72);
    putchar(105);
    putchar(33);
    putchar(10);
    return 0;
}

